[package]
name = "payments-engine"
version = "0.1.0"
edition = "2021"

description = "CLI CSV Payment Engine"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
